### ISSUE TITLE
TS2688: Cannot find type definition file for 'cypress' - while executing any cy tests

### ISSUE THREAD

**Issue by Nimzi-Git** [badeball/cypress-cucumber-preprocessor#1169] opened 2024-03-20 15:56 UTC
### Current behavior

When running any cypress tests, the test is failing with the below error:

> [1] [tsl] ERROR
> [1]       TS2688: Cannot find type definition file for 'cypress'.
> [1]   The file is in the program because:
> [1]     Entry point of type library 'cypress' specified in compilerOptions

The test does not run after this error. 

### Desired behavior

It should run the test cases

### Test code to reproduce
**Believe this issue is a known one and it has been happening since upgraded the cypress versions - any help on this would be really appreciated**

It has been happening since the version upgrade

### Versions
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/31898886/2364f3fb-78a7-437e-b90f-75b0fabd7ebb)

* **Cypress version**: 10.11
* **Preprocessor version**: 4.0.1
* **Node version**: 18.19

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2024-03-20 16:25
You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment] 2024-04-01 10:37
> Believe this issue is a known one [..]

Doesn't matter, I can't help you unless you show me what you're doing and so far you've managed to provide literally nothing. 
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2024-04-01 10:37 UTC
Labels: needs reproduction
