### ISSUE TITLE
At v15.1.5 and beyond tests hang 

### ISSUE THREAD

**Issue by DevKhaira** [badeball/cypress-cucumber-preprocessor#995] opened 2023-04-12 20:33 UTC
### Current behavior

[cypress hang failure.txt](https://github.com/badeball/cypress-cucumber-preprocessor/files/11215700/cypress.hang.failure.txt)
Cypress hangs after version 15.1.4

### Desired behavior

not to hang 

### Versions

* **Cypress version**: >12
* **Preprocessor version**: > 15.1.4
* **Node version**:16.17.1

### Checklist

- [- ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ -] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ -] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2023-04-13 04:47
Hey, and thanks for reporting this issue. You need however to adhere to the guidelines for [reporting issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports). Please read through it and update your issue accordingly.

**Comment by DevKhaira** [comment] 2023-04-13 07:59
Sure sorry was quite late. Will make a block example over the weekend because it might be a certain configuration.

**Comment by DevKhaira** [comment] 2023-05-26 12:34
hey @badeball https://www.loom.com/share/b0e6068b870348d6961eb20890c40d1e I thought I'd give you a loom to show apart of the issue. 
Sorry been crazy busy, so haven't been able to spin up my own environment. Let me know if theres something I can do to help you reproduce further :)

**Comment by badeball** [comment] 2023-05-26 12:51
This isn't what I'm looking for. You need to provide a way for me to reproduce the behavior myself. You can read about this in the [contributing guidelines](https://github.com/badeball/cypress-cucumber-preprocessor/blob/c3824ec20cca99afbbf2312be5399588b597b195/CONTRIBUTING.md#reduced-test-case).

**Comment by badeball** [comment] 2023-07-16 08:44
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2023-07-16 08:44 UTC
Labels: needs reproduction
