### ISSUE TITLE
Specs are not pre-filtered by provided tag even though`filterSpecs` is set to `true`

### ISSUE THREAD

**Issue by ZeevKatz** [badeball/cypress-cucumber-preprocessor#1070] opened 2023-08-10 13:45 UTC
### Current behavior

I'm using NX to manage a monorepo of various Cypress projects based on TS.
When running the following command cypress still goes over each feature instead of filtering only the ones that contain scenarios tagged with `@smoke`:
```nx run my-app:e2e --baseUrl ... --env.tags=@smoke```

My cypress cucumber config looks like this:
```
  "stepDefinitions": [....],
  "pretty": {
    "enabled": true
  },
  "omitFiltered": true,
  "filterSpecs": true
  ```

### Versions

* **Cypress version**: 11.2.0
* **Preprocessor version**:18.0.3
* **Node version**:18.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2023-08-10 13:59
Are you sure you’re specifying tags though? `env.tags=@smoke` isn’t something I’m familiar with.

**Comment by ZeevKatz** [comment] 2023-08-10 14:04
Yeah I'm sure, fact that it filters the correct scenarios
The problem is that it goes over all the features instead of filtering just the relevant ones

**Comment by badeball** [comment] 2023-08-10 14:08
Then you need to provide a reproducible example.

**Comment by badeball** [comment] 2023-08-30 18:01
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2023-08-30 18:01 UTC
Labels: needs reproduction

**Comment by mohamed-a-huma** [comment] 2023-09-13 21:19
This issue is happening to me as well. Will try to provide a reproducible example and put here 

> Yeah I'm sure, fact that it filters the correct scenarios The problem is that it goes over all the features instead of filtering just the relevant ones

This is happening to me too! @ZeevKatz were you able to solve this or find a root cause?

**Comment by ANSHUL786** [comment] 2023-10-10 05:44
@badeball Ya its a problem

**Comment by jrutila** [comment] 2024-11-25 15:21
Anyone stumbling over here, please read the note here: https://docs.cypress.io/app/references/environment-variables#Option-4---env

> Multiple values must be separated by a comma, not a space. In some shells, like Windows PowerShell, you may need to surround the key/value pair with quotes: --env "cyuser=dummyUser,cypassword=dummyPassword".
