### ISSUE TITLE
When running a mixed set of specs, test reports exclude the test results of non-cucumber specs

### ISSUE THREAD

**Issue by serhatgemici** [badeball/cypress-cucumber-preprocessor#1171] opened 2024-03-26 14:28 UTC
### Current behavior

When I execute a set of mixed specs {cucumber, cy.js}, and check the reports, I see that there are only the results of the cucumber specs, and the cy.js spec test results are missing on html, json and messages reports. 

### Desired behavior

When a mixed suite is executed, it would be really great to have the test reports containining all tests results rather than excluding the results of the cy.js  type of mocha specs.

Being able to mix the spec types is really great, but only getting the partial test report out of a test run is kind of taking away the usefulness of that great feature.

### Test code to reproduce
To reproduce the issue on an isolated environment, all that's needed is to checkout to  this repo and follow the steps below:
https://github.com/serhatgemici/specResultsExcludedInTestReports

the repo contains a reduced test case based on [esbuild-cjs example](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-cjs) with mixed spec files {1 cucumber and 1 non-cucumber} 

> npm i

and then 
> npm run test:chrome

Check the test reports in
> reports/html/
> reports/json/

--> Test reports only contain cucumber specs.

### Versions

* **Cypress version**: 13.7.1
* **Preprocessor version**: 20.0.2
* **Node version**: v20.11.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2024-03-26 15:13
This is unfortunately intended behavior. There's no good way of representing a non-cucumber spec in a cucumber report. Closing as it's not a bug.

**Closed as completed by badeball** 2024-03-26 15:13 UTC
