### ISSUE TITLE
bad behavior since 2.4 

### ISSUE THREAD

**Issue by mnesti** [badeball/cypress-cucumber-preprocessor#389] opened 2020-06-12 08:34 UTC
Hi 

When I keep the 2.3.1 version all work fine.

I have some bad behavior since 2.4  (Tested with cypress from 4.4.1 until 4.8)
- First case 
The tags is less respected : 
a .feature with two scenari and one tag by scenario.
If I request only one tag, the two scenari was played.

- Second case  error message following
```
visit https://xxxxxxxx
get #_username
type xxxxxxxx
get #_password
get .form > .btn1 > [name="submit"]
click
form sub --submitting form--
page load --waiting for new page to load--
new url https://xxxxxxxxxxx
viewport 1366, 768
visit https://xxxxxxxxxx

then function(){}
    1) "after each" hook for "MyUsers manipulation (DM5)"


  0 passing (11s)
  1 pending
  1 failing

  1) DocumentManager MyUser right and Archive manipulations
       "after each" hook for "MyUsers manipulation (DM5)":
     CypressError: `cy.click()` failed because it requires a DOM element.

The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.get()`

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `DocumentManager MyUser righ...`
      at ensureElement (https://www-/__cypress/runner/cypress_runner.js:155429:24)
      at validateType (https://www-/__cypress/runner/cypress_runner.js:155253:16)
      at Object.ensureSubjectByType (https://www-/__cypress/runner/cypress_runner.js:155295:11)
      at pushSubjectAndValidate (https://www-/__cypress/runner/cypress_runner.js:162959:15)
      at Context.<anonymous> (https://www-/__cypress/runner/cypress_runner.js:163287:18)
  From Your Spec Code:
      at Context.eval (https://www-/__cypress/tests?p=cypress/support/index.js:913:6)


```

![image](https://user-images.githubusercontent.com/23173008/84481782-e24d2580-ac96-11ea-8d04-9168585525ca.png)

Thanks for your help

**Comment by lgandecki** [comment] 2020-06-15 07:56
Sorry for the troubles. Any chance to have a small reproduction for both?

**Comment by mnesti** [comment] 2020-06-15 08:26
No Problem, Congratulation for this preprocessor is a pleasure to use.

Context:
Docker: container on debian with this package.json 

```
{
    "cypress-cucumber-preprocessor": {
        "nonGlobalStepDefinitions": true
    },
    "devDependencies": {
        "@4tw/cypress-drag-drop": "^1.3.1",
        "cypress-failed-log": "^2.6.2",
        "cypress-file-upload": "^4.0.4",
        "cypress-image-snapshot": "^3.1.1",
        "cypress-plugin-tab": "^1.0.5",
        "mocha": "<=5.2.0",
        "mocha-multi-reporters": "^1.1.7",
        "mochawesome": "^4.1.0",
        "mochawesome-merge": "^2.1.0",
        "mochawesome-report-generator": "^4.1.0",
        "node-xlsx": "^0.15.0"
    },
    "dependencies": {
        "core-js": "^3.6.4",
        "cypress": "^4.2.0",
        "cypress-cucumber-preprocessor": "^2.0.1",
        "cypress-downloadfile": "^1.2.0",
        "express": "^4.17.1",
        "fs-extra": "^8.1.0",
        "xmlhttprequest": "^1.8.0"
    }

```
 

the .feature look like:

``` cucumber
@documentmanager @practitioner @fr
Feature: XXXXX

@right
  Scenario: XXX
    Given  ---- 
    When  ---- 
    Then  ---- 

@archive
Scenario: YYYY
    Given  ---- 
    When ---- 
    Then  ---- 
```
if I use this launcher

`  ./node_modules/.bin/cypress-tags run -e TAGS='@right'`

the test tagged @archive is running too with the last cucumber version.

**Comment by jvanoostveen** [comment] 2020-06-15 11:44
Same here, I would love to update our Cypress, but this issue is blocking for now.

**Comment by lgandecki** [comment] 2020-06-15 12:23
@jvanoostveen is updating cypress problematic or this plugin?

The only change in 2.4.0 is change to how cypress-tags work, do you also use that to start the tests?

**Comment by jvanoostveen** [comment] 2020-06-15 12:53
Euhm no not really, and I mixed `@cypress/webpack-preprocessor` with this one as a required update. Although I had issues with a previous combination of the three (cypress, the webpack preprocessor and the cucumber preprocessor). Spend a fair amount of debugging into the inner workings until I gave up and later, updating all three, making it work again. Thus not so sure where the issue resides :).
It was a 'let's update all' action :) - but I might try downgrading the cucumber preprocessor.

**Comment by jvanoostveen** [comment] 2020-06-15 13:16
The issue with 2.3.1 is that it will only run the first scenario and not even notice there are more scenarios in Cypress 4.8. This seems to be fixed in 2.4 or 2.5, except it will crash on the scenario's after the first. Maybe I should submit a new issue for this :).

**Comment by lgandecki** [comment] 2020-06-15 13:21
Yes, please, create a separate issue with small reproductions with possible

**Comment by dimas-lex** [comment] 2020-07-23 11:25
The same, Tried to run https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example example with cypress 4.9.0 and failed to run it

```
Oops...we found an error preparing this test file:  
  cypress\support\index.js 

The error was: 
WebpackOptionsValidationError: Invalid configuration object.
```

**Comment by badeball** [comment] 2022-04-10 16:21
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Closed by badeball** 2022-04-10 16:21 UTC
