### ISSUE TITLE
Failed to read cypress.json file after update to 4.0.1

### ISSUE THREAD

**Issue by mysticdevx** [badeball/cypress-cucumber-preprocessor#519] opened 2021-03-03 15:01 UTC
### Current behavior

After updating cypress-cucumber-preprocessor to 4.0.1, I started getting error as in the below:
this is how I run my cypress test:

`$ cypress-tags run -e TAGS='@wip'`

and this is what I got in log:

```
Failed to read cypress.json, using default configuration
Spec files:  cypress/integration/**/*.feature

```

p.s. although the log mentions that it can not read cypress.json, base url and other settings in cypress.json seems applied in my tests.

### Versions

* **Cypress version**: tried with 5.6.0 and 6.6.0 
* **Preprocessor version**: 4.0.1
* **Node version**: v15

**Comment by badeball** [comment] 2021-03-03 15:34
I'm not able to reproduce the issue. Please provide a repository containing a minimal example that illustrates it.

**Comment by mysticdevx** [comment] 2021-04-08 15:15
@badeball 
previously i could not create reproducible example, and did not have more explanation. but now I can give more detail. I have tried with v4.0.3 and cypress 7.0.0 again, still the problem persists (v.2.5.4 works as expected, without any problem):

Explanation:
our framework is a monorepo, i.e. we have apps in upper level directories, and e2e framework as sub directories. thus, there are two package.jsons:
the upper level is the app level, package.json contains all dependencies including cypress-cucumber-preprocessor., cypress etc.
the sub directory has the cypress framework, its package.json has all yarn scripts, cypress-cucumber-preprocessor related settings etc.
currently if I move cypress.json file to upper level, it reads (but no use because cypress fw is not there)
but when cypress.json is its original place, it can not read. 
this problem was not there when i was using version 2.5.4
can you help on this issue?

**Comment by badeball** [comment] 2021-04-08 16:50
> can you help on this issue?

No, unfortunately not.

This just doesn't help me in any way in narrowing down the problem.

Most problems posted here aren't at all problems with the preprocessor,  but really just user-problems. Unless you can provide me a minimal example that illustrates the issue, I'm just going to assume exactly that.

**Comment by mysticdevx** [comment] 2021-04-08 16:52
ok, I will prepare a minimal example and post later today

**Comment by mysticdevx** [comment] 2021-04-09 08:42
@badeball Hi again, 
below is a minimal example to reproduce the issue. 
[sample-repo](https://github.com/mysticdevx/cucumber-preprocessor-example)
Best.

**Comment by badeball** [comment] 2021-04-09 09:34
I'm able to reproduce your issue. It seems like `cypress-tags.js` makes strong assumptions about its own location ([ref](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/v4.0.3/cypress-tags.js#L43)), which with Yarn workspaces is different.

That whole file is pretty ripe for a good cleanup. However, due to lack of test coverage for the cases it attempts to cover, I'm hesitant in even touching it myself. It's essentially a re-implementation of Cypress' own way of resolving specs, which takes a whole bunch of variables into account and the number of cases is huge.

Unless someone else wants to take ownership of that, I don't see Yarn workspaces being properly supported any time soon.

**Comment by mysticdevx** [comment] 2021-04-09 11:52
thank you for the explanation. can you @lgandecki help on this issue?

**Comment by mysticdevx** [comment] 2021-06-11 08:47
Hi @lgandecki 
cypress-cucumber-preprocessor v 4.1.2 
the problem still persists :( any help will be appreciated.
Thank you

**Comment by badeball** [comment] 2022-04-10 16:13
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Closed by badeball** 2022-04-10 16:13 UTC
