### ISSUE TITLE
Getting error "Step implementation missing for "<feature step>""

### ISSUE THREAD

**Issue by rahulbendale03** [badeball/cypress-cucumber-preprocessor#1163] opened 2024-02-26 15:08 UTC
I have configure the Cypress cucumber and created different folder structure for feature and step definition. But getting missing error. I have attached folder structure.

### Desired behavior
![Config_Cypress](https://github.com/badeball/cypress-cucumber-preprocessor/assets/43116075/5853556f-7386-4939-a2ea-11182c34fd5d)

### Versions
"@badeball/cypress-cucumber-preprocessor": "^20.0.1",
"@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
"cypress": "^13.6.6",
* **Node version**: 10.2.4

**Comment by badeball** [comment] 2024-02-26 15:49
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment] 2024-04-01 10:34
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2024-04-01 10:34 UTC
Labels: needs reproduction
