### ISSUE TITLE
Expected there to be a timestamp for current step - New Issue

### ISSUE THREAD

**Issue by acLebert** [badeball/cypress-cucumber-preprocessor#1249] opened 2024-10-09 15:28 UTC
Current behavior
I am encountering an error in my test suite while using @badeball/cypress-cucumber-preprocessor. The error occurs specifically in the after each hook, and causes all remaining tests in the current suite to be skipped. The following stack trace is generated:

javascript
Copy code
Error: Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Backbar and Commission`
Here is the relevant portion of my test where the issue occurs:

stack trace
at createError (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/error.js:10:0) at fail (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/assertions.js:14:0) at assert (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/assertions.js:20:0) at assertAndReturn (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/assertions.js:23:0) at Context.afterEachHandler (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:610:0) at Context.eval (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:207:0)

The error occurs within the Backbar and Commission test suite.
The issue seems to be connected with tracking timestamps for steps, but there are no issues reported within the steps themselves.
This happens after the test completes, during the after each hook, leading to test suite failures.
This might be a one off thing since this is used throughout 300+ spec files, and this happened this 1 time. But im following instructions to report this. 

Desired behavior
The test should execute the after each hook without causing errors. Timestamps for steps should be correctly registered and the suite should not skip tests due to missing timestamps in steps.

Test code to reproduce
The error occurs in my test suite that utilizes @badeball/cypress-cucumber-preprocessor with the following configuration:

Cypress is set up to run a suite named Backbar and Commission, which involves API interceptions and assertions related to backbar and commission calculations.
The issue occurs specifically in the afterEach() hook of this suite.
Unfortunately, I am unable to share the full codebase, but I will attempt to outline the flow that triggers this error:

Test initiates and performs its steps.
The after each hook is invoked for cleanup tasks.
The error is thrown related to missing timestamp information for the current step, and subsequent tests are skipped.
If necessary, I can provide more details on my environment or test setup.

Versions
Cypress version: 13.15.0
Preprocessor version: 20.1.2
Node version: 18.16.0
Checklist
 I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
 I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
 I'm not using cypress-cucumber-preprocessor@4.3.1 (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).
 
 
 
 More info I found within the output
 
 Estimated: 1 minute, 31 seconds
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="103.276" tests="5" failures="2">
  <testsuite name="Root Suite" timestamp="2024-10-09T14:24:26" tests="0" file="cypress/features/SalonIris/BackbarAndCommission.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Backbar and Commission" timestamp="2024-10-09T14:24:26" tests="5" time="103.129" failures="2">
    <testcase name="Backbar and Commission Correct employee appears in Backbar and Commission section" time="17.772" classname="Correct employee appears in Backbar and Commission section">
    </testcase>
    <testcase name="Backbar and Commission Adjust backbar amount of a service" time="21.458" classname="Adjust backbar amount of a service">
    </testcase>
    <testcase name="Backbar and Commission Adjust commission value of a service" time="21.649" classname="Adjust commission value of a service">
    </testcase>
    <testcase name="Backbar and Commission Commission and Backbar fields are disabled for a closed ticket" time="16.879" classname="Commission and Backbar fields are disabled for a closed ticket">
    </testcase>
    <testcase name="Backbar and Commission Discard dialogue appears after editing commission without saving" time="0.001" classname="Discard dialogue appears after editing commission without saving">
      <failure message="Cannot read properties of undefined (reading &apos;id&apos;)" type="TypeError"><![CDATA[TypeError: Cannot read properties of undefined (reading 'id')
    at Context.eval (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:328:0)]]></failure>
    </testcase>
    <testcase name="Backbar and Commission &quot;after each&quot; hook for &quot;Discard dialogue appears after editing commission without saving&quot;" time="0.001" classname="&quot;after each&quot; hook for &quot;Discard dialogue appears after editing commission without saving&quot;">
      <failure message="Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Backbar and Commission`" type="Error"><![CDATA[Error: Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Backbar and Commission`
    at createError (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/error.js:10:0)
    at fail (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/assertions.js:14:0)
    at assert (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/assertions.js:20:0)
    at assertAndReturn (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/assertions.js:23:0)
    at Context.afterEachHandler (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:610:0)
    at Context.eval (webpack:///../../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:207:0)]]></failure>
    </testcase>
  </testsuite>
</testsuites>

Just ingnore the first scenario failure as it was flaky and did end up passing in the additional run after.

**Comment by badeball** [comment] 2024-10-09 17:26
Duplicate of https://github.com/badeball/cypress-cucumber-preprocessor/issues/1222, thus closing.

In any case, the information you've provided unfortunately doesn't help me to reproduce the issue.

**Closed as completed by badeball** 2024-10-09 17:26 UTC
