### ISSUE TITLE
Failed to create JSON report

### ISSUE THREAD

**Issue by ollie-bud** [badeball/cypress-cucumber-preprocessor#1009] opened 2023-04-27 20:10 UTC
### Current behavior

Fails on `JSON.Parse()` when attempting to generate a report after a test run.

```jsonc
// .cypress-cucumber-preprocessorrc.json
{
  "stepDefinitions": "cypress/support/stepDefinitions",
  "messages": { "enabled": false },
  "json": { "enabled": true }
}
```

```ts
// cypress.config.ts
import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  e2e: {
    specPattern: "cypress/e2e/**/*.{js.jsx,ts,tsx,feature}",
    chromeWebSecurity: false,
    videoUploadOnPasses: false,
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions,
    ): Promise<Cypress.PluginConfigOptions> {
      await addCucumberPreprocessorPlugin(on, config);
      on("file:preprocessor", createBundler({ plugins: [createEsbuildPlugin(config)] }));
      return config;
    },
  },
});

```

```bash
An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

SyntaxError: Unexpected token { in JSON at position 74
    at JSON.parse (<anonymous>)
    at {filepath}/node_modules/@badeball/cypress-cucumber-preprocessor/lib/add-cucumber-preprocessor-plugin.js:120:33
    at Array.map (<anonymous>)
    at afterRunHandler ({filepath}/node_modules/@badeball/cypress-cucumber-preprocessor/lib/add-cucumber-preprocessor-plugin.js:120:14)
```

```js
// node_modules/@badeball/cypress-cucumber-preprocessor/lib/add-cucumber-preprocessor-plugin.js:120:14
const messages = (await fs_1.promises.readFile(messagesPath))
   .toString()
   .trim()
   .split("\n")
   .map((line) => JSON.parse(line));
```

If I log above the loop, it shows that it gets a little bit in to the huge attachment message and cuts early - rather than continuing with the rest of it. In one example it got to the second line (which was an attachment) and 40959~ characters into the message before failing to parse (which makes sense as it's split midway through).

```
... 9x+s9Gavfvv+lCgortWrlfD360MYJfS2Xy6XaumbV1jXJHB6mxMQ4pacljem8ZLQaG1sUExOliIjg+3ePx6Mf//R9tbfb9OjDd2jVitwJ366pMF2OS6fNFdOxhP8kb3BQWfMmteJfIAcP7NFTT39dWbNy9OI3XtEXX3yq0pLBrYcNBoNWrFyvzXfdJ6PRqJqaSl27FjhMV1NTqZZmq7be95i6u7tUUty/HW5iUooee+I5hYeb1dHeFjDc19rarBPHD2jzXfdr/Ya75HDYdSX/omy23hmmBoNBi5es1KbNW2UwGHXq5OFBAcbiousquHFFufMXB92eqKho3f/gE4qOjlVnZ4eu5F/wP+ZyOXX50nmtW79Jjz3+nHbven9QpUSDwaB16zdr3rwF8njcunBhat9TAAAAABiK0WgIWKlqrMv5lh1roMRsDtfs2SNvo2AwaNCFr9q6Rn91tuAVAL0tgucHeXwgk8k4qouNlZV1+sXrOyRJDz90R9CZuQcOnpXknfU63N8sLMyk1JREpaaM/rrDeBjNZ+BWZjIZlZKSoJSU0V3ANhg07YJWt5rICHPAagATKSYmaszhk8jIoW8oTodxZzz9+jefqbCwQgkJsXrl29sD3lCtb7Aq/4q3StySxXMDrmc0NztGE0AfbyaTcdRt+iZjnRER5lHtZ/tKSIhVwk1UKYuKihzTawfa1wdbLiE+ZswB4Jhoy6iDvBNloo9TBvJVlLwZw41p42U6vU+jNdXHcsBopCUm6KJK/a2AA/G1+A3UAvhWEhZmuqnzILM5fNShwYGvP16MRqOioiJHHZCbziIjIxQZeXMt1A0G3XJ/F2C0jEaj5uRkaE5Oxk2t52bPGSTvceXCBdlauGBq9i+xsdFauniutHjs6zCZjMrKnKGszBljXsd4vSdjtWrlfBUUVuratVI9/MD6CQ2Mm0wmZcxMVsbM0QUtx8Nw1QIlqay8Tu3tNlkizVq4YOJaL8Nr2gQAQ11jY71+8/ ...
```

From the above string, it was split after `NdXHcsBopCUm6KJK/a2AA/G1` 🤷 

### Desired behavior

Test results generated successfully

### Test code to reproduce

Really happy to create if needed - but just want to check I'm not being a silly billy first 😃 

### Versions

* **Cypress version**: 12.6.0
* **Preprocessor version**: 16.0.3
* **Esbuild Preprocessor version**: 2.2.0
* **Node version**: 18

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2023-04-27 20:23
Hey, and thanks for reporting this issue, this sounds strange. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by peter-erdei-intland** [comment] 2023-04-28 09:54
Hi @badeball , I found it the message.ndjson is generated but the cucumber json is a 0 bytes file. Maybe something is wrong if there are too much tests are running (more than 600). Is there any way to execute a command to create this json from the generated message.ndjson ? Also I saw lines like that:

![image](https://user-images.githubusercontent.com/108263504/235116515-361394f6-6238-4929-82fd-e71f6f10a17d.png)

can it be expected ?

Thank you very much for all your support! You are trully amazing :)

**Comment by badeball** [comment] 2023-04-28 12:31
@peter-erdei-intland, it's impossible to say given the provided information. Do you have 25 hooks? Then yes, this is expected.

If you think you've found a bug, then you need to open up a separate issue and follow the contributing guidelines.

> Is there any way to execute a command to create this json from the generated message.ndjson ?

No, but I like the idea and I'll definitely put it on my list.

**Comment by peter-erdei-intland** [comment] 2023-05-22 06:49
Hi @badeball , with your new version, and with the latest cypress, the issue is gone on ci, thank you very much for all your effort :)

**Comment by badeball** [comment] 2023-07-16 08:44
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2023-07-16 08:44 UTC
Labels: needs reproduction
