### ISSUE TITLE
Error: Unexpected state in afterSpecHandler: step-started 

### ISSUE THREAD

**Issue by suneelfm-tandem** [badeball/cypress-cucumber-preprocessor#1166] opened 2024-02-28 07:02 UTC
### Current behavior

Getting **Unexpected state in afterSpecHandler: step-started** error, when the all other remaining tests has skipped due to any error as shown in image. If the tests doesn't skipped then I am not seeing this error. Getting this error for the version 20.0.0 and above, not for the lower versions.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/132546945/e2a7eee5-a9c0-41a9-a634-7e20945eed77)

### Test code to reproduce
I have given the scenario where the issue is. I hope test code is not required.

### Versions

* **Cypress version**: v13.6.5
* **Preprocessor version**: v20.0.1
* **Node version**: v16.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2024-02-28 10:43
> I hope test code is not required.

It is. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment] 2024-04-01 10:35
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2024-04-01 10:35 UTC
Labels: needs reproduction
