### ISSUE TITLE
Feature request: Print steps in output when running in headless mode

### ISSUE THREAD

**Issue by alexmonteirocastro** [badeball/cypress-cucumber-preprocessor#848] opened 2022-09-29 15:27 UTC
### Current behavior

Currently only the Scenario names are being logged in the output. 

### Desired behavior

I would like to see the steps names being logged into the output

### Test code to reproduce

This is a feature request

Is there a way to tweak the configuration to make this happen? 

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2022-09-30 12:11
Duplicate of https://github.com/badeball/cypress-cucumber-preprocessor/issues/810.

**Closed as completed by badeball** 2022-09-30 12:11 UTC
