### ISSUE TITLE
Tests don't run when I migrated from cypress-cucumber-preprocessor to @badeball/cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by KarineBrandelli** [badeball/cypress-cucumber-preprocessor#1115] opened 2023-11-09 16:42 UTC
### Current behavior

The cypress present this error:

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/108953489/839138be-e0e3-44ea-847e-e133335bc322)

### Test code to reproduce

This is my `cypress.config.ts` file, wich is in my root directory:

```ts
import { defineConfig } from 'cypress'
import type * as Webpack from 'webpack'
import { devServer } from '@cypress/webpack-dev-server'
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor'

const webpackConfig = (
  cypressConfig: Cypress.PluginConfigOptions
): Webpack.Configuration => {
  return {
    resolve: {
      extensions: ['.tsx', '.jsx', '.ts', '.js']
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: [/node_modules/],
          use: [
            {
              loader: 'ts-loader',
              options: { transpileOnly: true }
            }
          ]
        },
        {
          test: /\.ts$/,
          exclude: [/node_modules/],
          use: [
            {
              loader: 'babel-loader'
            }
          ]
        },
        {
          test: /\.feature$/,
          use: [
            {
              loader: '@badeball/cypress-cucumber-preprocessor/webpack',
              options: cypressConfig
            }
          ]
        }
      ]
    }
  }
}

export default defineConfig({
  component: {
    specPattern: '**/*.feature',
    devServer(devServerConfig) {
      return devServer({
        ...devServerConfig,
        framework: 'react',
        webpackConfig: webpackConfig(devServerConfig.cypressConfig)
      })
    },
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config)

      return config
    },
    env: {
      codeCoverage: {
        exclude: ['cypress/**/*.*']
      },
      TAGS: '@focus'
    }
  }
})
```

My test files are in my `cypress/integration/` folder, for example:

```sh
Actions.feature

Feature: Actions - Default

    I want to use default Actions

    Background: Render component
        Given  I render Actions default

    @focus
    Scenario: I click on confirm
        When I click on button name 'confirm-action'
        Then I expect 'ActionsConfirm' spy to have been called 1 times

    @focus
    Scenario: I click on cancel
        When I click on button name 'cancel-action'
        Then I expect 'ActionsCancel' spy to have been called 1 times

    @focus
    Scenario: I click on confirm using cy selector
        When I click on cy element 'test-confirm'
        Then I expect 'ActionsConfirm' spy to have been called 1 times

    @focus
    Scenario: I click on cancel using cy selector
        When I click on cy element 'test-cancel'
        Then I expect 'ActionsCancel' spy to have been called 1 times
```

### Versions

* **Cypress version**: 13.5.0
* **Preprocessor version**: 19.1.0
* **Node version**: 18.12.1

Is there any aditional setup?

I'm using React + Webpack so I've followed this config: https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/ct-webpack-react-ts

@badeball

**Comment by badeball** [comment] 2023-11-09 17:01
You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment] 2024-01-17 09:44
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2024-01-17 09:44 UTC
Labels: needs reproduction
