### ISSUE TITLE
Migrating Cypress test from old version to latest version throws error Expected to find a global registry 

### ISSUE THREAD

**Issue by scrumvisualize** [badeball/cypress-cucumber-preprocessor#860] opened 2022-10-14 02:23 UTC
### Current behavior
I am trying to migrate my existing Cypress BDD tests from 8.7.0 version to latest version 10.10.0.  I have installed the required libraries and amended the settings. I was having an old node version 12 + version, now updated to node v18.4.0 and tried again. Couldn't find any pointers to resolve similar issue, so any advise would be really helpful.

Following is my automation folder structure: 
* ** feature file location** 

> tests/cypress/e2e/ login/login.feature 

* ** Step definition location** 
Imported in the step definition file 
` import { Given, When, Then, Before, After} from "@badeball/cypress-cucumber-preprocessor";`
> tests/cypress/stepDefinitions/login.cy.js

Added `e2e.js` file under tests/cypress/support folder: 

```
// Import commands.js using ES2015 syntax:
import './commands'
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
})
```
Added `.cypress-cucumber-preprocessorrc.json`file in to the test root folder
```

{
  "stepDefinitions": [
    "[filepath].{js,ts}",
    "tests/cypress/stepDefinitions/**/*.{js,ts}",
    "tests/cypress/e2e/[filepath]/**/*.{js,ts}",
    "tests/cypress/e2e/[filepath].{js,ts}",
    "tests/cypress/support/step_definitions/**/*.{js,ts}"
  ]
}

```

Below is my cypress.config.js file: 
```
const { defineConfig } = require("cypress");
const webpackPreprocessor = require('@cypress/webpack-preprocessor');
const addCucumberPreprocessorPlugin = require("@badeball/cypress-cucumber-preprocessor");
const dotenvPlugin = require("cypress-dotenv");

async function setupNodeEvents(on, config) {
    await addCucumberPreprocessorPlugin.addCucumberPreprocessorPlugin(on, config);

    const options = {
        webpackOptions: {
            module: {
                rules: [
                    {
                        test: /\.feature$/,
                        use: [
                            {
                                loader: '@badeball/cypress-cucumber-preprocessor/webpack',
                                options: config,
                            },
                        ],
                    },
                ],
            },
        },

    };

    on('file:preprocessor', webpackPreprocessor(options));

    return config;
}

module.exports = {
    default: defineConfig({
        e2e: {
            baseUrl: "https://book.test.co",
            specPattern: "tests/cypress/e2e/**/*.feature",
            supportFile: false,
            setupNodeEvents,
        },
    }),
    setupNodeEvents,
};
```

Error Details
![image](https://user-images.githubusercontent.com/5972626/195744773-aa3cb9ea-9d94-41dc-b6c0-ff56c5f3abba.png)

### Desired behavior
Hope to run the BDD feature file without errors 

### Test code to reproduce

Removed following items from the automation framework

  *  **plugin/index.js ** file 
  *  **cypress.json ** file 
uninstalled old `cypress-cucumber-preprocessor `from the project

### Versions

* **Cypress version**:  Cypress 10.10.0
* **Preprocessor version**: @badeball/cypress-cucumber-preprocessor 11.4.0
* **Node version**: v18.4.0
* **cypress/webpack-preprocessor**: 5.14.0
* **OS**: Ubuntu 20.04.3 LTS

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2022-10-14 07:36
You need to provide me with a complete, but minimal and runnable example.

**Comment by DenFin** [comment] 2022-10-14 19:26
I'm having the same issue with the 'Expected to find a global registry' error. I created a minimal setup with cypress and cucumber. Maybe this might help: https://github.com/DenFin/minimal-cypress-cucumber-setup

**Comment by badeball** [comment] 2022-10-16 20:53
@DenFin, in your case you can remove `js` from `specPattern`. You're now trying to run step definitions as if they're the test (they're not).

**Comment by scrumvisualize** [comment] 2022-10-16 23:15
@badeball  In my case , I didn't have js in my specPattern. Don't know if that is helpful in case. This is my settings: `specPattern: "tests/cypress/e2e/**/*.feature",`

**Comment by scrumvisualize** [comment] 2022-10-19 00:30
> I'm having the same issue with the 'Expected to find a global registry' error. I created a minimal setup with cypress and cucumber. Maybe this might help: https://github.com/DenFin/minimal-cypress-cucumber-setup
@DenFin  Have you got an idea or work around on how to handle this issue ?  I did one one more thing, I have downgraded node version to ` v14.16.1` and update to the latest version of `"@badeball/cypress-cucumber-preprocessor": "^13.0.2"`, then clear the app data and tried again, but still the same error. I am kind of stuck at the moment.

**Comment by DenFin** [comment] 2022-10-20 18:07
@scrumvisualize actually removing `js` from the `specPattern` solved the problem for me

**Comment by smorstabilini** [comment] 2023-03-13 10:51
@scrumvisualize have you found any solution?

**Comment by badeball** [comment] 2023-04-28 08:11
Closing due to lack of reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2023-04-28 08:11 UTC
