### ISSUE TITLE
cannot run different given in a single feature file

### ISSUE THREAD

**Issue by Amofe2** [badeball/cypress-cucumber-preprocessor#942] opened 2023-02-08 14:59 UTC
### Current behavior
When different Given statement is used in a single feature file, cypress automatically picks the first and replace the subsequent ones with the first given statement, even thought the implementation is supposed to be different

### Desired behavior
It should be able to run different given statement, just as it is on the cucumber official page that more than one given statement can be used in a feature file. what if we have a situation where we need to have more than one given statement & each given statement has a diff code implementation, just like this:

// ViewAllSpots.feature

Feature: View all study spots

Scenario: View all study spots in Toronto by default
**Given I'm on the main page**
And location is disabled
When the page loads
Then I should see the map of Toronto with at least one spot displayed

Scenario: View spots based on my location
**Given I'm on the admin page**
And location is enabled
And I'm in San Francisco
When the page loads
Then I should see the map of San Francisco with at least one spot displayed

I noticed cypress automatically makes the first given thesame for the rest given, more like it can only run a given statement in a single feature

### Versions

* **Cypress version**: 10.1.0
* **Preprocessor version**: 15.1.2
* **Node version**: 16.14.1

**Comment by badeball** [comment] 2023-02-08 15:15
You need to provide an example that reproduces this behavior.

**Comment by badeball** [comment] 2023-04-28 08:11
Closing due to lack of reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2023-04-28 08:11 UTC
