### ISSUE TITLE
Cypress + cucumber: No test found when run "cypress open"

### ISSUE THREAD

**Issue by carri747** [badeball/cypress-cucumber-preprocessor#935] opened 2023-01-26 16:51 UTC
HI,

I have tried to set up a project with cypress / cypress-cucumber-preprocessor and typescript but it's not working totally.

When I run "cypress run --spect ..."  this command work properly and I got the result properly "All steps passed" but when I run "cypress open e2e --browser chrome" and I click in the test I got a error "Cypress could not detect tests in this file."
```
Error: Build failed with 1 error:
C:\Dev\Hilco\node_modules\esbuild\lib\main.js:255:12: ERROR: Invalid option in build() call: "watch"
    at failureErrorWithLog (C:\Dev\Hilco\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Dev\Hilco\node_modules\esbuild\lib\main.js:953:16
    at responseCallbacks.<computed> (C:\Dev\Hilco\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (C:\Dev\Hilco\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (C:\Dev\Hilco\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

And I don't know why
My package.json file:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "cypress:runner": "cypress open --e2e --browser chrome",
    "test": "cypress run --spec \"**/*.feature\"",
    "cypress:execution": "cypress run --spec cypress/e2e/features/*",
    "cypress:execution-tags": "cypress run --env tags=@mobile",
    "cypress:execution-allure": "cypress run --env allure=true",
    "allure:clear": "rm -r allure-results/ allure-report cypress/screenshots || true",
    "allure:report": "allure generate allure-results --clean -o allure-report",
    "allure:history": "mv -f allure-report/history allure-results/history && rm -r allure-report || true"
  },
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "15.1.2",
    "cypress": "12.4.0",
    "typescript": "4.9.4"
  },
  "dependencies": {
    "@bahmutov/cypress-esbuild-preprocessor": "2.1.5",
    "@cypress/xpath": "2.0.3",
    "@shelex/cypress-allure-plugin": "2.34.0",
    "cypress-xpath": "2.0.1",
    "esbuild": "0.17.4",
    "ts-loader": "9.4.2"
  }
}
```
My cypress.config.ts

```
async function setupNodeEvents(on, config) {
    // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
    await preprocessor.addCucumberPreprocessorPlugin(on, config);

    on(
        'file:preprocessor',
        createBundler({
            plugins: [createEsbuildPlugin.default(config)]
        })
    );
    allureWriter(on, config);

    // Make sure to return the config object as it might have been modified by the plugin.
    return config;
}

module.exports = defineConfig({
    e2e: {
        setupNodeEvents,
        specPattern: '**/*.{feature,features}',
        videosFolder: 'out/videos',
        screenshotsFolder: 'out/screenshots',
        baseUrl: 'https://www.google.com,
        defaultCommandTimeout: 30000,
        requestTimeout: 30000,
        chromeWebSecurity: false,
        env: {
            allureReuseAfterSpec: true
        }
    }
});
```
My .cypress-cucumber-preprocessorrc.json file:

```
{

  "json": {
    "enabled": false,
    "output": "jsonlogs/log.json",
    "formatter": "cucumber-json-formatter.exe"
  },
  "messages": {
    "enabled": false,
    "output": "jsonlogs/messages.ndjson"
  },
  "html": {
    "enabled": false
  },
  "stepDefinitions": [
    "[filepath]/**/*.{js,ts}",
    "[filepath].{js,ts}",
    "cypress/e2e/step_definitions/*.{js,ts}",
    "[filepath]\\***.{js,ts}",
    "[filepath].{js,ts}",
    "cypress\\e2e\\step_definitions\\*.{js,ts}"
  ]
}
```

My feature file
```
Feature: Test
    Scenario: Test
        Given I navigate to google page
```
My step definition:
```
import { Given } from '@badeball/cypress-cucumber-preprocessor';

Given('I navigate to main page', () => {    
    cy.visit('https://www.google.com/');
});
```

My structure
```
cypress
|- e2e
|----- features
|----- step_definitions
|-  fixtures
|-  integration
|-  plugin
|-  support
```

What am I doing wrong?

Thank you in advance

![image](https://user-images.githubusercontent.com/22347831/214899162-619e22d5-1c31-46c3-b075-5dacf059025d.png)

**Comment by badeball** [comment] 2023-01-26 17:24
Duplicate of https://github.com/badeball/cypress-cucumber-preprocessor/issues/929.

**Closed as completed by badeball** 2023-01-26 17:24 UTC

**Comment by carri747** [comment] 2023-01-27 08:12
Thank you 
I've changed my esbuild version and works
