### ISSUE TITLE
Types of Property Setup are incompatabile

### ISSUE THREAD

**Issue by QuantariusRay** [badeball/cypress-cucumber-preprocessor#1110] opened 2023-10-30 20:00 UTC
### Current behavior

Getting an error that Types of property "setup" are incompatible. 

<img width="915" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/31900736/03423b11-62af-4bfa-9cf6-2434087d53ab">

I'm currently using these versions:
"@badeball/cypress-cucumber-preprocessor": "^18.0.6",
"@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
"cypress": "13.3.3",

### Desired behavior

Be able to build/run the project.

### Test code to reproduce

Copy/Pasted the setup code in the repo.

```
async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}
```

### Versions

* **Cypress version**: 13.3.3
* **Node version**: 18.8.8
* Using Angular 15 if that matters.

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2023-10-31 08:06
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by dcantu96** [comment] 2023-12-07 23:13
I have the same issue for a react library @QuantariusRay were you able to fix this?

**Comment by badeball** [comment] 2024-01-17 09:44
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2024-01-17 09:44 UTC
Labels: needs reproduction
