### ISSUE TITLE
V17.0.0 not working:  before:spec event error

### ISSUE THREAD

**Issue by PlAlina** [badeball/cypress-cucumber-preprocessor#1013] opened 2023-05-08 09:17 UTC
### Current behavior

After upgrading  cypress-cucumber-preprocessor to v17.0.0 I receive the following error on cypress run:

_

> An error was thrown in your plugins file while executing the handler for the before:spec event.
> 
> The error we received was:
> 
> Error: Unexpected state in beforeSpecHandler: received-envelopes (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
>     at createError (.......\node_modules\@badeball\cypress-cucumber-preprocessor\dist\helpers\error.js:9:12)
>     at beforeSpecHandler (.......\node_modules\@badeball\cypress-cucumber-preprocessor\dist\plugin-event-handlers.js:197:43)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)

_

### Desired behavior

Cypress should run the features.

### Test code to reproduce
Upgrade   @badeball/cypress-cucumber-preprocessor": to 17.0.0 and run the tests

### Versions

* **Cypress version**: 12.9.0  
* **Node version**: 18.16.0
* **Preprocessor version**: 3.0.2
* Config:
> const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
> const browserify = require("@badeball/cypress-cucumber-preprocessor/browserify");

**Comment by badeball** [comment] 2023-05-08 10:36
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by ejbartelds** [comment] 2023-05-11 09:51
We updated to V17.0.0 on 2-may-2023. Today was the first time (as far as I can see) that we encountered this issue. It did not re-occur on re-runs, which makes it near impossible to make a minimal repro.

- Cypress version 12.12.0
- Node 18.16.7

**Comment by samuel-gomez** [comment] 2023-06-02 10:06
Hello, i have the same issue, you can reproduce with this starter : https://github.com/Pirlouit/cypress-starter-kit

**Comment by badeball** [comment] 2023-06-02 10:47
Hi @samuel-gomez, that appears to be a separate issue (notice the slightly different error message). I've opened #1028 to track this.

**Comment by badeball** [comment] 2023-07-16 08:45
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Closed as completed by badeball** 2023-07-16 08:45 UTC
Labels: needs reproduction
