### ISSUE TITLE
Consult about before / after hooks with features files

### ISSUE THREAD

**Issue by marcrecor** [badeball/cypress-cucumber-preprocessor#1090] opened 2023-09-06 14:02 UTC
### Current behavior

before() and after() hooks are executed before each feature

### Desired behavior

- **before()** and **after()** hooks should be executed before / after **all test**

- **beforeFeature()** and **afterFeature()** hooks should be executed before / after **each feature**

### Test code to reproduce

I have this hook on my repository to clean artifacts folder before the execution

`
before(function () {
  if (executionConfig.clean_artifacts) {
    cy.task("deleteArtifactsFolder");
  }
});
`

When I run all test, this hook is executed before each feature.

### Versions

* **Cypress version**: 12.14.0
* **Preprocessor version**: 17.2.0
* **Node version**: 16

**Comment by badeball** [comment] 2023-09-06 20:06
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by MDG-JHowley** [comment] 2023-10-04 10:04
If I'm understanding correctly we had a similar requirement.

you could create your own `beforeFeature()` hook like this:

```javascript
import { Before } from '@badeball/cypress-cucumber-preprocessor';

/**
 * Is similar to Cypress' `before()` hook, but is re-run when a test is retried (e.g. `@retries(runMode=1)`)
 *
 * Utilises the cucumber plugin `Before()` hook for consistency (mixing mocha and cucumber hooks seems to cause
 * issues in execution order, reporting and especially during retries)
 *
 * Additionally runs within the context of a test instead of before the test has been created and therefore failures
 * in this hook will still get reported in cucumber based json reports
 * e.g. `  Hook failures can't be represented in JSON reports, thus none is created for ${spec.relative}.`
 *
 * Because we use `before()` as a place to setup test state this can be the cause of assertion failures.
 * Therefore it's important to support cypress' retry functionality to make our suites more reliable.
 *
 * Inspired by:
 * https://github.com/cypress-io/cypress/issues/19458
 * https://stackoverflow.com/questions/71285827/cypress-e2e-before-hook-not-working-on-retries
 */
export const retryableBeforeFeature = (fn: () => void) => {
  let shouldRun = true;
  let beforeHookResult = false;

  // we use Before from cucumber pre-processor as cypress will run this on retry attempt
  // we just abort early if we detected that it's already run to ensure this is only run once
  // i.e. replicating Cypress' `before()` rather than `beforeEach()`
  Before(function () {
    // console.log({ step: 1, shouldRun, beforeHookResult });

    if (!shouldRun) {
      if (!beforeHookResult) {
        this.skip();
      }
    }
    if (shouldRun) {
      shouldRun = false;

      fn();
    }
  });

  /**
   * This Hook will only run if the previous one passed so is a simple way of determining if the passed `fn()` was successful or not.
   * Due to Cypress's method of semi-asynchrnous comand chaining we can't await or rely on a return value
   */
  Before(function () {
    // console.log({ step: 2, shouldRun, beforeHookResult });
    beforeHookResult = true;
  });

  // When a test fails we flip the `shouldRun` flag back to true
  // so when cypress retries and runs the `Before()` before
  // the test that failed, we'll run the `fn()` logic once more.
  Cypress.on('test:after:run', (result) => {
    if (result.state === 'failed') {
      if (result.currentRetry < result.retries) {
        shouldRun = true;
      }
    }
  });
};
```

Your command log will get a bit messy but other than that it's fine

**Comment by badeball** [comment] 2023-11-08 19:06
Closing due to lack of a reproducible example. I have little to no desire to speculate as to what you mean here.

**Closed as completed by badeball** 2023-11-08 19:06 UTC
Labels: needs reproduction
