### ISSUE TITLE
Error: Missing preprocessor event handlers

### ISSUE THREAD

**Issue by unirora** [badeball/cypress-cucumber-preprocessor#1026] opened 2023-05-29 19:36 UTC
### Current behavior

Making changes to support cypress-cloud for parallel execution of cypress tests. While parallel execution is functioning correctly, it is throwing the following error and causes all the tests to fail.

**Error: Missing preprocessor event handlers (this usally means you've not invoked `addCucumberPreprocessorPlugin()` or not returned the config object in `setupNodeEvents()`)** 

### Desired behavior

Cypress e2e tests should execute parallel without any issue

### Test code to reproduce

**cypress.config.ts**

```
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor';
import browserify from '@badeball/cypress-cucumber-preprocessor/browserify';
import { defineConfig } from 'cypress';

export default defineConfig({
e2e: {
async setupNodeEvents(on, config) {
			await addCucumberPreprocessorPlugin(on, config);

			on(
				'file:preprocessor',
				browserify(config, {
					typescript: require.resolve('typescript'),
					browserifyOptions: {
						paths: ['cypress/'],
					},
				}),
			);
			config = install(on, config);
                         return config;
		},
		specPattern: 'cypress/e2e/**/*.feature',
	},
});
```
### Versions

* **Cypress version**: 12.13.0
* **badeball/cypress-cucumber-preprocessor version**: 17.2.0
* **Node version**: v16.17.1
*  **@cypress/browserify-preprocessor version**: 3.0.2

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment] 2023-05-29 20:04
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment] 2023-07-16 08:46
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

In any case, your answer probably resides at [docs/event-handlers.md: On event handlers](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md).

**Closed as completed by badeball** 2023-07-16 08:46 UTC
Labels: needs reproduction

**Comment by dheerajpiplani** [comment] 2023-07-19 02:14
@badeball - I am also experiencing the same issue. Using cypress latest version and not able to run my feature files.
(cypress.config.js file)
const { defineConfig } = require("cypress");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const nodePolyfills = require("@esbuild-plugins/node-modules-polyfill").NodeModulesPolyfillPlugin;
const addCucumberPreprocessorPlugin = require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const setConfigFile = require('./cypress/support/setConfigFile');

async function setupNodeEvents (on, config) {
  await addCucumberPreprocessorPlugin(on, config);
  const file = config.env.configFile || "";
  on(
    'file:preprocessor',
    createBundler({
      plugins: [nodePolyfills(), createEsbuildPlugin(config)],
    })
  );

  on("before:browser:launch", (browser = {}, launchOptions) => {
    if (browser.family === "chromium" && browser.name !== "electron") {
      launchOptions.args.push("--incognito");
    }

    if (browser.name === "electron") {
      launchOptions.preferences.incognito = true;
    }
    return launchOptions;
  });
  return setConfigFile(file);
}

module.exports = defineConfig({
  e2e: {
    setupNodeEvents,
    specPattern: '**/*.{feature,features}',
    excludeSpecPattern: '*.js'
  },
  defaultCommandTimeout: 15000,
  taskTimeout: 100000,
  pageLoadTimeout: 150000,
  viewportWidth: 1280,
  viewportHeight: 720
});

    cypress-cucumber-preprocessor: "^17.1.1",
    cypress-esbuild-preprocessor: "^2.1.3",
    esbuild-plugins/node-modules-polyfil": "^0.1.4",

  "cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "cypress/e2e/[filepath].{js,ts}",
      "cypress/support/step_definitions/**/*.{js,ts}"
    ]
  }
Could you please take a look?

**Comment by badeball** [comment] 2023-07-19 05:39
@dheerajpiplani you need to open a new issue and follow the template.
